# Generated by Django 5.1.7 on 2025-04-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferitem',
            name='final_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transferitem',
            name='initial_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
