# Generated by Django 5.1.7 on 2025-04-02 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counteragent',
            name='personal_discount',
        ),
    ]
