# Generated by Django 5.1.7 on 2025-04-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('is_store', models.BooleanField()),
                ('is_main', models.BooleanField(default=False)),
            ],
        ),
    ]
