# Generated by Django 5.2 on 2025-04-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
