# Generated by Django 5.2 on 2025-04-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='priority',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
