# Generated by Django 5.1.7 on 2025-04-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordering_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
