# Generated by Django 5.2 on 2025-04-04 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_remove_counteragent_personal_discount'),
        ('sales', '0003_sale_saleproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_amount', models.PositiveIntegerField()),
                ('new_amount', models.PositiveIntegerField()),
                ('change_time', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_changes', to='people.employee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='sales.order')),
                ('order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='sales.orderproduct')),
            ],
        ),
    ]
